// Rentor site data — B2C / B2B copy in ES + EN
export const RENTOR_COPY = {
  es: {
    b2c: {
      nav: { product: "Producto", how: "Cómo funciona", pricing: "Precios", brokers: "Corredoras", signin: "Entrar", cta: "Empezar gratis" },
      audienceToggle: { b2c: "Propietario", b2b: "Corredora" },
      hero: {
        eyebrow: "AUTOADMINISTRATIVO · SIN INTERMEDIARIOS",
        title1: "Deja de perseguir pagos.",
        title2: "Publica, visita, firma",
        title3: "cobra",
        title4: "— todo desde Rentor.",
        sub: "La plataforma que reemplaza Excel, WhatsApp y la planilla del contador. Para propietarios que gestionan entre 1 y 10 arriendos sin perder el control.",
        ctaPrimary: "Publicar mi primer arriendo",
        ctaSecondary: "Ver demo de 2 min",
        metrics: [
          { k: "TIEMPO PROMEDIO", v: "3 min", d: "publicar un arriendo" },
          { k: "PROPIETARIOS ACTIVOS", v: "+2.400", d: "en todo Chile" },
          { k: "TASA DE MOROSIDAD", v: "1.8%", d: "vs 8% mercado" },
        ],
      },
      steps: {
        eyebrow: "CÓMO FUNCIONA · 3 PASOS",
        title1: "De lista a firmado en",
        title2: "menos de 14 días.",
        sub: "Sin reuniones, sin notaría, sin imprimir nada. Rentor te acompaña desde que decides arrendar hasta el primer pago.",
        items: [
          { n: "01", t: "Publica en 3 minutos", d: "Sube fotos, define canon y servicios incluidos. Rentor lo publica automáticamente en los portales más visitados de Chile." },
          { n: "02", t: "Coordina visitas sin WhatsApp", d: "Los interesados agendan directamente en tu calendario. Rentor verifica identidad y pre-filtra con score de arrendatario." },
          { n: "03", t: "Firma digital, sin notaría", d: "Contrato generado con tus cláusulas, firma electrónica avanzada. Inicias cobros automáticos el mismo día." },
        ],
      },
      dash: {
        eyebrow: "EL PRODUCTO · SCREENSHOTS REALES",
        title: "Un solo lugar para todas tus propiedades.",
        sub: "Diseño oscuro, data densa, atajos de teclado. Construido para propietarios que realmente lo van a usar todos los meses.",
        feat: [
          { t: "Cobro automático", d: "Recordatorios, cargos y comprobantes, sin tocar un dedo." },
          { t: "Firma avanzada", d: "Contratos con validez legal, guardados para siempre." },
          { t: "Reportes SII-ready", d: "Ingresos, gastos y retenciones listos para tu contador." },
          { t: "Mantenciones", d: "Los arrendatarios reportan, tú apruebas el gasto." },
        ],
      },
      pricing: {
        eyebrow: "PRECIOS · CLP MENSUAL · IVA INCLUIDO",
        title: "Cobra tus arriendos, no por usar Rentor.",
        sub: "Sin letra chica. Puedes pausar o cancelar cuando quieras. 30 días gratis en todos los planes.",
        monthly: "Mensual",
        annual: "Anual · −20%",
        plans: [
          { name: "SOLO", price: 4990, priceAnnual: 3990, desc: "Para quien gestiona 1 propiedad y no quiere más planillas.", feats: ["1 unidad activa", "Publicación en portales", "Firma electrónica simple", "Cobro automático", "Soporte por mail"], cta: "Empezar gratis" },
          { name: "PORTAFOLIO", price: 14990, priceAnnual: 11990, desc: "Para propietarios con 2-10 unidades que quieren automatización real.", feats: ["Hasta 10 unidades", "Todo lo de Solo", "Firma electrónica avanzada", "Score de arrendatarios", "Reportes SII-ready", "Soporte priorizado"], cta: "Empezar 30 días gratis", featured: true },
          { name: "CORREDORA", price: null, desc: "Para corredoras con 20+ propiedades. White-label, multi-usuario, API.", feats: ["Propiedades ilimitadas", "Multi-usuario con roles", "White-label + subdominio", "API & integraciones", "Dashboard por agente", "Onboarding dedicado"], cta: "Contáctanos", contact: true },
        ],
        note: "¿No te decides? Todos los planes incluyen 30 días gratis, sin tarjeta.",
      },
      cta: {
        title: "Tu próximo arriendo, sin fricción.",
        sub: "Crea tu cuenta en 60 segundos. Publica la primera propiedad hoy.",
        primary: "Empezar gratis",
        secondary: "Hablar con ventas",
      },
      footer: {
        tagline: "SaaS autoadministrativo para arriendos en Chile.",
        product: ["Cómo funciona", "Precios", "Para corredoras", "Changelog"],
        resources: ["Calculadora ahorro", "Plantillas contrato", "Blog", "Estado del sistema"],
        legal: ["Términos", "Privacidad", "Seguridad"],
        col: { product: "PRODUCTO", resources: "RECURSOS", legal: "LEGAL" },
      },
    },
    b2b: {
      hero: {
        eyebrow: "PARA CORREDORAS · 20–200 PROPIEDADES",
        title1: "Reemplaza Excel,",
        title2: "no tu modelo de negocio.",
        sub: "Rentor se integra a tu operación y tú sigues siendo la cara visible. White-label, multi-usuario y automatización real — a una fracción del costo de enterprise.",
        ctaPrimary: "Agendar demo · 20 min",
        ctaSecondary: "Ver calculadora de ahorro",
        metrics: [
          { k: "COSTO OPERATIVO", v: "−75%", d: "vs gestión manual" },
          { k: "MOROSIDAD", v: "−6 pts", d: "de 8% a 2% promedio" },
          { k: "CAPACIDAD", v: "+2.5×", d: "sin contratar más gente" },
        ],
      },
      steps: {
        eyebrow: "PARA TU CORREDORA · OPERACIÓN COMPLETA",
        title1: "Una plataforma para",
        title2: "toda tu cartera.",
        sub: "Desde el primer prospecto hasta la liquidación mensual. Cada agente ve solo lo suyo, tú ves todo.",
        items: [
          { n: "01", t: "Carga tu cartera en un día", d: "Importa propiedades desde Excel. Cada propiedad se asigna al agente responsable con un click." },
          { n: "02", t: "Tu marca, no la nuestra", d: "Logo, colores y subdominio propios. Los arrendatarios ven a tu corredora, no a Rentor." },
          { n: "03", t: "Liquidación automática", d: "Cálculo de comisión, gastos y neto al propietario. Estado de cuenta listo para enviar cada mes." },
        ],
      },
      dash: {
        eyebrow: "DASHBOARD CORREDORA",
        title: "Ve toda tu operación en tiempo real.",
        sub: "Performance por agente, morosidad agregada, propiedades vacantes. La información que antes vivía en 12 planillas distintas.",
        feat: [
          { t: "Multi-usuario", d: "Roles: admin, agente, asistente, solo lectura." },
          { t: "White-label", d: "Tu marca en emails, portal y subdominio propio." },
          { t: "API & webhooks", d: "Conecta con tu contabilidad o CRM actual." },
          { t: "Reportes por agente", d: "KPIs individuales, bonos configurables." },
        ],
      },
      pricing: {
        eyebrow: "PLAN CORREDORAS · POR PROPIEDAD",
        title: "Pricing que crece contigo, no contra ti.",
        sub: "Sin implementación de 6 meses, sin contrato anual obligatorio. Agenda una demo y te armamos un plan a la medida de tu cartera.",
      },
      cta: {
        title: "Llevemos tu corredora al siguiente nivel.",
        sub: "Una llamada de 20 minutos. Te mostramos el producto y calculamos cuánto ahorrarías.",
        primary: "Agendar demo",
        secondary: "Descargar one-pager",
      },
    },
  },
  en: {
    b2c: {
      nav: { product: "Product", how: "How it works", pricing: "Pricing", brokers: "Brokers", signin: "Sign in", cta: "Get started" },
      audienceToggle: { b2c: "Landlord", b2b: "Broker" },
      hero: {
        eyebrow: "SELF-SERVE · NO MIDDLEMEN",
        title1: "Stop chasing rent.",
        title2: "List, show, sign,",
        title3: "collect",
        title4: "— all from Rentor.",
        sub: "The platform that replaces Excel, WhatsApp and your accountant's spreadsheet. Built for landlords with 1 to 10 units who want control without the overhead.",
        ctaPrimary: "List my first rental",
        ctaSecondary: "Watch 2-min demo",
        metrics: [
          { k: "AVG. SETUP TIME", v: "3 min", d: "to publish a listing" },
          { k: "ACTIVE LANDLORDS", v: "2,400+", d: "across Chile" },
          { k: "DELINQUENCY RATE", v: "1.8%", d: "vs 8% market" },
        ],
      },
      steps: {
        eyebrow: "HOW IT WORKS · 3 STEPS",
        title1: "From listed to signed in",
        title2: "under 14 days.",
        sub: "No meetings, no notary, no printing. Rentor walks you from the decision to rent through the first payment.",
        items: [
          { n: "01", t: "List in 3 minutes", d: "Upload photos, set rent and included services. Rentor publishes on Chile's top portals automatically." },
          { n: "02", t: "Book tours without WhatsApp", d: "Prospects book directly on your calendar. Rentor verifies identity and pre-filters with a tenant score." },
          { n: "03", t: "Digital signature, no notary", d: "Contract generated with your clauses, advanced e-signature. Start automated collections the same day." },
        ],
      },
      dash: {
        eyebrow: "THE PRODUCT · REAL SCREENSHOTS",
        title: "One place for every property.",
        sub: "Dark UI, dense data, keyboard shortcuts. Built for landlords who actually use it every month.",
        feat: [
          { t: "Auto-collect", d: "Reminders, charges and receipts, hands-free." },
          { t: "Advanced e-sign", d: "Legally binding contracts, stored forever." },
          { t: "Tax-ready reports", d: "Income, expenses and withholdings for your accountant." },
          { t: "Maintenance", d: "Tenants report issues, you approve the cost." },
        ],
      },
      pricing: {
        eyebrow: "PRICING · USD MONTHLY",
        title: "Collect rent, not fees for Rentor.",
        sub: "No fine print. Pause or cancel anytime. 30-day free trial on every plan.",
        monthly: "Monthly",
        annual: "Annual · −20%",
        plans: [
          { name: "SOLO", price: 6, priceAnnual: 5, currency: "USD", desc: "For folks managing one property who are done with spreadsheets.", feats: ["1 active unit", "Portal publishing", "Simple e-signature", "Auto-collect", "Email support"], cta: "Get started" },
          { name: "PORTFOLIO", price: 19, priceAnnual: 15, currency: "USD", desc: "For landlords with 2-10 units who want real automation.", feats: ["Up to 10 units", "Everything in Solo", "Advanced e-signature", "Tenant scoring", "Tax-ready reports", "Priority support"], cta: "Start 30-day trial", featured: true },
          { name: "BROKER", price: null, desc: "For brokerages with 20+ properties. White-label, multi-user, API.", feats: ["Unlimited properties", "Multi-user with roles", "White-label + subdomain", "API & integrations", "Per-agent dashboards", "Dedicated onboarding"], cta: "Contact us", contact: true },
        ],
        note: "Still undecided? All plans include 30 days free, no card required.",
      },
      cta: {
        title: "Your next tenancy, friction-free.",
        sub: "Sign up in 60 seconds. List your first property today.",
        primary: "Get started",
        secondary: "Talk to sales",
      },
      footer: {
        tagline: "Self-serve rental management for Chile.",
        product: ["How it works", "Pricing", "For brokers", "Changelog"],
        resources: ["Savings calculator", "Contract templates", "Blog", "System status"],
        legal: ["Terms", "Privacy", "Security"],
        col: { product: "PRODUCT", resources: "RESOURCES", legal: "LEGAL" },
      },
    },
    b2b: {
      hero: {
        eyebrow: "FOR BROKERS · 20–200 PROPERTIES",
        title1: "Replace Excel,",
        title2: "not your business model.",
        sub: "Rentor plugs into your operation and you stay the face of the brand. White-label, multi-user, real automation — at a fraction of enterprise cost.",
        ctaPrimary: "Book a 20-min demo",
        ctaSecondary: "Try the savings calculator",
        metrics: [
          { k: "OPERATIONAL COST", v: "−75%", d: "vs manual workflow" },
          { k: "DELINQUENCY", v: "−6 pts", d: "from 8% down to 2%" },
          { k: "CAPACITY", v: "+2.5×", d: "without new hires" },
        ],
      },
      steps: {
        eyebrow: "FOR YOUR BROKERAGE · FULL OPS",
        title1: "One platform for",
        title2: "your whole portfolio.",
        sub: "From first prospect to monthly settlement. Every agent sees their own, you see everything.",
        items: [
          { n: "01", t: "Load your portfolio in a day", d: "Import properties from Excel. Each one is assigned to a responsible agent with one click." },
          { n: "02", t: "Your brand, not ours", d: "Your logo, colors and custom subdomain. Tenants see your brokerage, not Rentor." },
          { n: "03", t: "Automated settlement", d: "Commission, expenses and net to landlord calculated. Monthly statement ready to send." },
        ],
      },
      dash: {
        eyebrow: "BROKER DASHBOARD",
        title: "See your whole operation in real time.",
        sub: "Per-agent performance, aggregate delinquency, vacant units. The info that used to live in 12 different spreadsheets.",
        feat: [
          { t: "Multi-user", d: "Roles: admin, agent, assistant, read-only." },
          { t: "White-label", d: "Your brand in emails, portal and your own subdomain." },
          { t: "API & webhooks", d: "Connect with your accounting or CRM." },
          { t: "Per-agent reports", d: "Individual KPIs, configurable bonuses." },
        ],
      },
      pricing: {
        eyebrow: "BROKER PLAN · PER PROPERTY",
        title: "Pricing that grows with you, not against you.",
        sub: "No 6-month onboarding, no mandatory annual contract. Book a demo and we'll tailor a plan to your portfolio.",
      },
      cta: {
        title: "Let's take your brokerage to the next level.",
        sub: "A 20-minute call. We show you the product and calculate your savings.",
        primary: "Book a demo",
        secondary: "Download one-pager",
      },
    },
  },
};
